### ISSUE TITLE
Tilde Input

### ISSUE THREAD

**Issue by ogleboondoggle** [codicocodes/speedtyper.dev#101]
One race required an input of a tilde, but did not accept my input.
![Tilde issue](https://user-images.githubusercontent.com/114028142/194927650-97bb4faa-b218-42d1-b098-99c92c0700f1.jpg)

**Comment by codicocodes** [comment]
You probably pressed the wrong key, it's just a normal input field that takes any key press.

![image](https://user-images.githubusercontent.com/76068197/195178176-0ae1f474-db98-464a-bf0c-cfd40457c379.png)

**Comment by ogleboondoggle** [comment]
I had tried multiple keys, including  1. ` 2. ~ (shift + ~) 3. multiple
random letters. I'll attempt it again in the future. Thanks for the
response.

**Comment by codicocodes** [comment]
No problem!

I was thinking right now about a potential feature to make this experience better. Obviously even if you are typing the wrong character, you don't think so which is resulting in a bad user experience.

I was thinking after several failed attempts. It would be interesting to make it possible for the user to kind of inspect their input, to see what character they are typing. 

This could avoid a frustrating experience, and you could more easily show if there is actually a bug or not.

What do you think? Is it a reasonable idea?
