### ISSUE TITLE
Make profile page mobile optimized

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/speedtyper.dev#108]
This is the current profile page:

https://speedtyper.dev/profile/codicocodes

![image](https://user-images.githubusercontent.com/76068197/195990190-997c65bc-1033-4845-b317-3bdfb62320b6.png)

This page should be mobile optimized. 

Requirements:
- It does not overlap with the Navbar (related to #107 but out of scope to do a wider solution)
- There is no side scroll. The chart scales down to fit a mobile screen.
- There is no superfluous vertical scroll

**Comment by UditNS** [comment]
Hi, I am interested in working on this.

I also want to what were thinking of design to be?

**Comment by codicocodes** [comment]
Thanks for picking it up :+1: 

The design should look something similar to this in the end:

![image](https://user-images.githubusercontent.com/76068197/195990846-7f5a5ad9-b2fb-4b66-ad89-2e5c16eb36d5.png)

With no regressions on the desktop view.

Current desktop view:

![image](https://user-images.githubusercontent.com/76068197/195990919-b360a27b-a6f3-4aae-a470-8c6ebb042b4c.png)

Let me know if you have any more questions, happy to clarify!

**Comment by UditNS** [comment]
I will do that

**Comment by codicocodes** [comment]
Something similar to this would look good as well: 
![image](https://user-images.githubusercontent.com/76068197/195991137-8a9a4404-e0c5-48b2-bbce-d12d7c958554.png)

**Comment by UditNS** [comment]
I am also thinking like this to make it in column

**Comment by UditNS** [comment]
Hi, 
I have installed node but I got an error is their any custom build. I used "npm run start"
<img width="1216" alt="Screenshot 2022-10-15 at 8 08 04 PM" src="https://user-images.githubusercontent.com/102902271/195992350-f0a97d09-7b32-4bcb-b19d-c4e23073b4be.png">

**Comment by codicocodes** [comment]
You should run `yarn` to build dependencies and then `yarn dev` to run the development environment.

**Comment by codicocodes** [comment]
To run next directly you have to have next installed globally, which I personally don't

**Comment by UditNS** [comment]
Thanks, get back to you once completed

**Comment by UditNS** [comment]
I cannot access the page
![Uploading Screenshot 2022-10-15 at 9.39.16 PM.png…]()

**Comment by UditNS** [comment]
I am not able to access the pages.
<img width="579" alt="Screenshot 2022-10-15 at 9 39 16 PM" src="https://user-images.githubusercontent.com/102902271/195996723-dd4acdf2-adba-4a0a-840e-9462f3e82605.png">

**Comment by Ovoda** [comment]
> I am not able to access the pages.
> <img alt="Screenshot 2022-10-15 at 9 39 16 PM" width="579" src="https://user-images.githubusercontent.com/102902271/195996723-dd4acdf2-adba-4a0a-840e-9462f3e82605.png">

Try accessing a real profile, like /profile/Ovoda (mine). Make sure the backend is running on your machine as well

**Comment by codicocodes** [comment]
There could be some issues with this still, as it would require not only having the back end running, but also having valid users with results in your local DB you can navigate to. Which means you have to configure github oauth as well (I have not documented this process yet)

:information_source: Should probably create a seed script to add dummy users and results, to make development easier. Not a high priority though.

**Comment by UditNS** [comment]
> There could be some issues with this still, as it would require not only having the back end running, but also having valid users with results in your local DB you can navigate to. Which means you have to configure github oauth as well (I have not documented this process yet)
> 
> ℹ️ Should probably create a seed script to add dummy users and results, to make development easier. Not a high priority though.

How can I do that
