### ISSUE TITLE
way to pick programming language?

### ISSUE THREAD

**Issue by mileycodeit** [codicocodes/speedtyper.dev#138]
I think its best if any programmer can pick their own programming language of choice when practicing typing?

**Comment by codicocodes** [comment]
There is already a way to pick a language

<img width="1081" alt="Screenshot 2023-02-27 at 06 55 29" src="https://user-images.githubusercontent.com/76068197/221485699-de4ebdce-774c-4ce8-b2ed-905266b54a65.png">
