### ISSUE TITLE
More code snippets for speedtyper.dev

### ISSUE THREAD

**Issue by WilliamFerns1** [codicocodes/speedtyper.dev#183]
## Problem:
I have been using Speedtyper.dev for around 4 - 6 months now, and I am truly fascinated by the idea. It is truly one of a kind: a touchtyping platform for practising your typing, specifically for developers. For typing an average of around 10 minutes daily for over 4 months, I constantly find myself typing the same code snippet.

## Why this matters: 
The reason it is worth fixing this problem, is because:
- Developers that visits speedtyper.dev on a daily basis find themselves typing the same code snippet over and over. It becomes repetitive and boring. It will enhance the user experience if there are more code snippets. 
- Competitors already have this. Although Monkeytype doesn't actually have code snippets, you can go up with complexity, from English10k, 20k, ect... (not entirely sure of the numbers, you get the point.)

## Recommendations:
I recommend having a "HTML" and "CSS" language option as well. Make so that when no language options are chosen, it also gives HTML and CSS code snippets occasionally.

## Solution:
To solve this specific problem, here are actionable steps for one of the contributors of this repository when making a pull request:
- [ ] identify where the code snippets are sourced from
- [ ] get a batch list of code snippets that are free to use (don't use code snippets from Github Repositories where they have strict licenses, preferably no license, or MIT license).
- [ ] add that code snippets to the resource pool (where all the code snippets are stored at. Not sure if this is in the actual repository, or in a database).
- [ ] Submit a Pull Request that fixes this issue, optionally attaching a recorded video showcasing the changes made.

**Comment by lcnlvrz** [comment]
I had this problem too, so i decided to fork and change `challenge.seeder.ts`. You just need to run it locally and ensure github token is defined in `.env`

Basically i just add the functionality to get file contents from any github repository and import it in speedtyper database as challenges

I hope it helps you

https://github.com/lcnlvrz/speedtyper.dev/commit/6247f66c616c1638bd20bfd6b1bc6639f2a0b960

**Comment by WilliamFerns1** [comment]
> I had this problem too, so i decided to fork and change `challenge.seeder.ts`. You just need to run it locally and ensure github token is defined in `.env`
> 
> Basically i just add the functionality to get file contents from any github repository and import it in speedtyper database as challenges
> 
> I hope it helps you
> 
> [lcnlvrz@6247f66](https://github.com/lcnlvrz/speedtyper.dev/commit/6247f66c616c1638bd20bfd6b1bc6639f2a0b960)

Great. Truly appreciate you sharing this. Will check it out and setup locally, and deploy as well. Truly appreciate it.
