### ISSUE TITLE
Feedback on the setup instructions

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/speedtyper.dev#22]
Follow the setup instructions [here](https://github.com/codicocodes/speedtyper.dev/blob/main/CONTRIBUTING.md#running-speedtyperdev) to run speedtyper locally and give feedback on the setup process.

**Comment by Ovoda** [comment]
CONTRIBUTING.md : 
In running > backend, /speedtyper-backend/ should be /backend/

**Comment by codicocodes** [comment]
> CONTRIBUTING.md : In running > backend, /speedtyper-backend/ should be /backend/

Thank you! Fixed.

**Comment by Ovoda** [comment]
Error on setting up the backend : 
when running `make install-backend-dependencies` or `yarn install` in the backend folder : 

`Users/{me}/Library/Caches/node-gyp/16.17.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?`

running on node v16.17.0, on M1 Macbook Pro

It seems like node 16 has trouble building native dependencies. (https://bytemeta.vip/repo/Azure/autorest/issues/4494)

Fix I found : Upgrade `tree-sitter` from `0.19.0` to `0.20.0` in package.json

**Comment by codicocodes** [comment]
> NB: only works on node v16 (investigating to fix it on v.17 and higher)

What do you mean by NB?

FYI I don't think we need to support a higher version than Node LTS. 

I'll upgrade tree-sitter to 0.20, feel free to post here or make a PR if you find something further.

**Comment by Ovoda** [comment]
Nb is for “nota bene”
And yes you’re right no need for support higher than LTS 😅
Thanks for the fix !

> > NB: only works on node v16 (investigating to fix it on v.17 and higher)
> 
> What do you mean by NB?
> 
> FYI I don't think we need to support a higher version than Node LTS.
> 
> I'll upgrade tree-sitter to 0.20, feel free to post here or make a PR if you find something further.

**Comment by codicocodes** [comment]
> Nb is for “nota bene” And yes you’re right no need for support higher than LTS 😅 Thanks for the fix !
> 
> > > NB: only works on node v16 (investigating to fix it on v.17 and higher)
> > 
> > 
> > What do you mean by NB?
> > FYI I don't think we need to support a higher version than Node LTS.
> > I'll upgrade tree-sitter to 0.20, feel free to post here or make a PR if you find something further.

Thanks for the find as well! ⭐

**Comment by codicocodes** [comment]
This has been open for 30 days now, closing for now! Thank you for the help on this @Ovoda
