### ISSUE TITLE
Migrate from img tags to next/image

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/speedtyper.dev#33]
Blocked on #29 

There are several instances of img tags in the repository. 

We should consider if we should either migrate from img tags to next/image or if we should disable the lint rule and continue using img tags. Any opinions?

**Comment by ronakmehtav** [comment]
The next/image should bring a bunch of image optimizations.

**Comment by Alcherith** [comment]
I wanna work on it. Can i work on this?
