### ISSUE TITLE
Make a favicon

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/speedtyper.dev#71]
Make a favicon for Speedtyper using this image, and add it to the repository

![image](https://user-images.githubusercontent.com/76068197/192356388-373e1739-90ab-46c6-a490-8021a0fae661.png)

**Comment by ronakmehtav** [comment]
I have opened a pull request resolving this.

**Comment by codicocodes** [comment]
Thank you @ronakmehtav, I will test it later!
