### ISSUE TITLE
Add wpm tooltip on ResultsChart

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/speedtyper.dev#87]
When hovering over a "dot" the trailing WPM for that second should show.

This component is accessed on /play2 after completing a challenge

[This](https://github.com/codicocodes/speedtyper.dev/blob/main/packages/webapp-next/modules/play2/components/ResultsChart.tsx) is the relevant component.

ChartJS documentation: https://www.chartjs.org/docs/latest/configuration/tooltip.html

![image](https://user-images.githubusercontent.com/76068197/193453351-80ec4f15-7e52-4607-b5d1-37b03d40d58d.png)

**Comment by Kenqz** [comment]
I can pick this up

**Comment by Kenqz** [comment]
Possible solution moving to react-chart.js instead of chart.js library since callbacks on default tooltips doesn't seem to execute.

`plugins: {
        tooltip: {
          enabled: true,
          intersect: true,
          mode: "nearest",
          position: "average",
          backgroundColor: "black",
          bodyColor: "#00FFFF",
          callbacks: {
            // title function doesn't execute
            title: (context): any => {
              // no console log output
              console.log(context);
            },
          },
        },
      },`
